esJavaOpts: -Xmx2G -Xms2G
imageTag: 7.12.0
minimumMasterNodes: 1
replicas: 1
resources:
  limits:
    memory: 8Gi
roles:
  data: "false"
  ingest: "false"
  master: "true"
  ml: "false"
  remote_cluster_client: "false"
readinessProbe:
  initialDelaySeconds: 600
volumeClaimTemplate:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
replicas: 1
minimumMasterNodes: 1
rbac:
  create: true
antiAffinity: "soft"
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: elasticsearch.magmalocal.com
