---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanadashboards
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanadata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanadatasources
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafanaproviders
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvpn
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promcfg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
---
